services:
  postgres:
    container_name: "dzen_postgres"
    image: postgres:16-alpine
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_dzen:/var/lib/postgresql/data
    restart: unless-stopped

  elasticsearch:
    container_name: "dzen_elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata_dzen:/usr/share/elasticsearch/data
    restart: unless-stopped

  redis:
    container_name: "dzen_redis"
    image: redis:7-alpine
    volumes:
      - redis_dzen:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped

  api:
    container_name: "dzen_api"
    build:
      context: .
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - elasticsearch
      - redis
    restart: unless-stopped

volumes:
  postgres_dzen:
  esdata_dzen:
  redis_dzen:
